name: Issue Notification

on:
  issues:
    types: [opened]

jobs:
  comments:
    name: comments issue
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Comment on the issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
        run: gh issue comment $ISSUE_URL -b "Bonjour $ISSUE_AUTHOR, nous avons bien pris en compte votre problème."
