name: Workflow du projet

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build, Test, et Run Application
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Installer les dépendances
        run: mvn install -DskipTests=true

      - name: Construire l'application
        run: mvn package

      - name: Exécuter les tests
        run: mvn test
        continue-on-error: false  # Bloque le job si les tests échouent

      - name: Upload du build
        if: ${{ success() && github.ref == 'refs/heads/main' }}  # Upload uniquement si les tests passent et si la branche est main
        uses: actions/upload-artifact@v4
        with:
          name: mon_app
          path: target/*.jar

  docker:
    name: Build et Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}  # Exécute uniquement si sur la branche main
    env:
      USERNAME: ${{ secrets.DOCKER_USERNAME }}
      PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest

  download:
    name: Télécharger et vérifier l'artefact
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}  # Exécute uniquement si sur la branche main

    steps:
      - name: Récupérer l'artefact
        uses: actions/download-artifact@v4
        with:
          name: mon_app

      - name: Lister les fichiers
        run: ls
